---
name: CI

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  ci:
    name: Run the integration tests
    runs-on: ubuntu-latest

    steps:
      # cache pulled docker images
      - uses: ScribeMD/docker-cache@0.3.3
        with:
          key: docker-${{ runner.os }}-${{ hashFiles('integration_tests/test_cnf_binary.py') }}
      - name: docker pull
        run : |
          docker pull registry.opensuse.org/opensuse/tumbleweed:latest
          docker pull registry.opensuse.org/opensuse/leap:15.5
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: 'pip'

      - name: install poetry
        run: |
          pip install --upgrade poetry
          poetry install

      - name: run pytest
        run: poetry run pytest -vv -n auto
        env:
          # force docker runtime to be used, so the docker-cache can fire up
          CONTAINER_RUNTIME=docker
