---
name: PR check

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  ci:
    name: Build and run the integration tests
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      -
        name: Install libsolv-dev, libclang-dev and cargo
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libsolv-dev libclang-dev cargo
          version: 1.0

      - uses: Swatinem/rust-cache@v2

      -
        name: debug
        run: |
          ls /usr/lib/x86_64-linux-gnu/libsolv.so* /usr/lib64/libsolv.a

      -
        name: Build cnf-rs
        run: cargo build
