---
name: PR check

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  ci:
    name: Build and run the integration tests
    runs-on: ubuntu-latest

    steps:

      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      -
        name: Install libsolv-dev, libclang-dev and cargo
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libsolv-dev libclang-dev cargo
          version: 1.0

      - uses: Swatinem/rust-cache@v2

      -
        name: Build cnf-rs
        run: cargo build

      - uses: docker/setup-buildx-action@v1

      -
        name: Build openSUSE Tumbleweed image
        uses: docker/build-push-action@v2
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: test/
          file: test/Dockerfile
          load: true
          push: false
          tags: local/cnf-rs-ci:latest

      -
        name: Integration test
        run: ./test/bats/bin/bats ./test

